---
abstract: 'Test::Class + Moose'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Class-Moose
requires:
  Moose: 0
  Test::Most: 0.31
resources:
  license: http://dev.perl.org/licenses/
version: 0
